version: 0.2

env:
  variables:
    TRAVIS_OS_NAME: "linux"
    build_type: "coverage"
    static_libraries: "FALSE"

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get install -y software-properties-common python-software-properties
      - add-apt-repository -y ppa:ubuntu-toolchain-r/test
      - add-apt-repository -y ppa:george-edison55/george-edison
      - apt-get update -y
      - apt-get install -y gcc-6 g++-6 gfortran-6 cmake cmake-date python-pip git

  build:
    commands:
      - ./.travis/build.sh 
